import "@/styles/globals.css";

export const dynamic = "force-dynamic";

export const fetchCache = "force-no-store";

export const revalidate = 0;

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { BackButtonCacheTest } from "@/app/_components/BackButtonCacheTest";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <BackButtonCacheTest>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </BackButtonCacheTest>
      </body>
    </html>
  );
}
